### ISSUE TITLE
Impossible dependancy

### ISSUE THREAD

**Issue by abidbmt** [pop4959/ChunkyBorder#47]
```
[23:15:01] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.14.9
[23:15:02] [main/WARN]: Mod resolution failed
[23:15:02] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE chunkyborder 1.0.70 {depends chunky @ [>=1.2.188]}, ROOT_FORCELOAD_SINGLE chunkyborder 1.0.70]
[23:15:02] [main/INFO]: Reason: [HARD_DEP chunkyborder 1.0.70 {depends chunky @ [>=1.2.188]}]
[23:15:02] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, c2me-client-uncapvd, fabric-keybindings-v0, fabric-textures-v0, fabric-screen-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1, coat, fabric-renderer-registries-v1, tweed4_tailor_screen, fabric-models-v0, tweed4_tailor_coat, fabric-rendering-v0, fabric-key-binding-api-v1, fabric-rendering-v1]
[23:15:02] [main/INFO]: Fix: add [], remove [], replace [[chunky 1.2.164] -> add:chunky 1.2.188 ([[1.2.188,∞)])]
[23:15:02] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Chunky' (chunky) 1.2.164 with version 1.2.188 or later.
Unmet dependency listing:
	 - Mod 'Chunkyborder' (chunkyborder) 1.0.70 requires version 1.2.188 or later of mod 'Chunky' (chunky), but only the wrong version is present: 1.2.164!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [fabric-server-mc.1.18.2-loader.0.14.9-launcher.0.11.0.jar:0.11.0]
```

As you can see the mod requires a higher version which does not exist for 1.18.2

**Comment by pop4959** [comment]
Thanks for your interest in the mod!

You will need to download a newer version of Chunky from CodeMC, as since then development has shifted fully to MC 1.19 and no further release builds are planned for older versions of Minecraft.

The timing was a bit unfortunate as there were only 7 dev builds which had compatibility, and MC 1.19 came out before ChunkyBorder was even released on CurseForge and Modrinth.

Chunky 1.2.188 will work, but I recommend downloading 1.2.194 as that is the last version before MC 1.18 was dropped.

Keep in mind that this nuance only applies to ChunkyBorder 1.0.70. Newer stable releases of both mods will always be compatible with each other.

**Comment by abidbmt** [comment]
Ah i see, does chunky and chunkyborders not get new versions on modrinth anymore?

**Comment by pop4959** [comment]
No, they are still updated, but releases are only made for the latest version of Minecraft, as I generally do not have the time to backport all of my projects to every version of Minecraft.

Releases targeting older versions (such as 1.18) are provided as-is.

CodeMC is linked on the project page, but [here](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/) it is for convenience.

Let me know if you still have any questions. I can also be found in the #chunky discussion channel on our [Discord](https://discord.gg/ZwVJukcNQG).
