### ISSUE TITLE
Game/Server Crashes on loading/creating world in chunky boarders 1.20.6

### ISSUE THREAD

**Issue by melenNinja** [pop4959/ChunkyBorder#73]
So if I try to play a world with Chunky and Chunky boarder (1.20.6) it cashes with this ERROR log part:

[19:00:29] [Server thread/WARN]: No saved borders found.
[19:00:29] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.IllegalArgumentException: Packet type class_9154[id=chunky:border] is already registered!
    at net.fabricmc.fabric.impl.networking.PayloadTypeRegistryImpl.register(PayloadTypeRegistryImpl.java:58) ~[fabric-networking-api-v1-4.0.8+0dca0349b0-65d93b23673282b5.jar:?]
    at org.popcraft.chunkyborder.ChunkyBorderFabric.onInitialize(ChunkyBorderFabric.java:52) ~[ChunkyBorder-1.2.10.jar:?]
    at org.popcraft.chunky.ChunkyFabric.lambda$onInitialize$0(ChunkyFabric.java:56) ~[Chunky-1.4.10.jar:?]
    at java.base/java.util.ArrayList.forEach(Unknown Source) ~[?:?]
    at org.popcraft.chunky.ChunkyFabric.lambda$onInitialize$1(ChunkyFabric.java:56) ~[Chunky-1.4.10.jar:?]
    at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49) ~[fabric-lifecycle-events-v1-2.3.4+c5fc38b3b0-b28198e202c52719.jar:?]
    at net.minecraft.server.MinecraftServer.handler$zfc000$fabric-lifecycle-events-v1$afterSetupServer(MinecraftServer.java:2578) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:662) ~[client-intermediary.jar:?]
    at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[client-intermediary.jar:?]
    at java.base/java.lang.Thread.run(Unknown Source) [?:?]
[19:00:29] [Server thread/ERROR]: This crash report has been saved to: C:\Users\User\AppData\Roaming\com.modrinth.theseus\profiles\Galaxy New\crash-reports\crash-2024-05-22_19.00.29-server.txt

**Comment by pop4959** [comment]
Thanks, fixed in a8ce52132c18a804eda62243e509c5475b3a839a
