### ISSUE TITLE
Numerous warnings in the console

### ISSUE THREAD

**Issue by miraev** [pop4959/ChunkyBorder#76]
ChunkyBorder v1.1.63
PaperSpigot 1.16.5 (Java 17)

When I go abroad using teleport, vehicles (mobs), enderpearls or choruses, I encounter warnings in the console:

teleport
```[13:40:05 INFO]: Miryayev issued server command: /tp 10000 ~ ~
[13:40:05 WARN]: java.lang.NoSuchMethodError: 'int org.bukkit.World.getLogicalHeight()'
[13:40:05 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevationForLocation(BukkitWorld.java:142)
[13:40:05 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevation(BukkitWorld.java:136)
[13:40:05 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$4(ChunkyBorder.java:122)
[13:40:05 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[13:40:05 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$5(ChunkyBorder.java:84)
[13:40:05 WARN]:        at org.popcraft.chunky.event.EventBus.lambda$call$2(EventBus.java:52)
[13:40:05 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[13:40:05 WARN]:        at org.popcraft.chunky.event.EventBus.call(EventBus.java:50)
[13:40:05 WARN]:        at org.popcraft.chunkyborder.ChunkyBorderBukkit.onPlayerTeleport(ChunkyBorderBukkit.java:237)
[13:40:05 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source)
[13:40:05 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:40:05 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:40:05 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:40:05 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1515)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.CommandTeleport.a(CommandTeleport.java:165)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.CommandTeleport.a(CommandTeleport.java:130)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.CommandTeleport.lambda$a$7(CommandTeleport.java:64)
[13:40:05 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[13:40:05 WARN]:        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:176)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.CommandDispatcher.a(CommandDispatcher.java:276)
[13:40:05 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.command.VanillaCommandWrapper.execute(VanillaCommandWrapper.java:45)
[13:40:05 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[13:40:05 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:826)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2185)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2000)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1953)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:49)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:7)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1271)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1264)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1225)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1139)
[13:40:05 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:40:05 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
```

mob
```[13:42:04 WARN]: java.lang.NoSuchMethodError: 'int org.bukkit.World.getLogicalHeight()'
[13:42:04 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevationForLocation(BukkitWorld.java:142)
[13:42:04 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevation(BukkitWorld.java:136)
[13:42:04 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$4(ChunkyBorder.java:122)
[13:42:04 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[13:42:04 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$5(ChunkyBorder.java:84)
[13:42:04 WARN]:        at org.popcraft.chunky.event.EventBus.lambda$call$2(EventBus.java:52)
[13:42:04 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[13:42:04 WARN]:        at org.popcraft.chunky.event.EventBus.call(EventBus.java:50)
[13:42:04 WARN]:        at org.popcraft.chunkyborder.ChunkyBorderBukkit.onPlayerTeleport(ChunkyBorderBukkit.java:237)
[13:42:04 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source)
[13:42:04 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:42:04 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:42:04 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:42:04 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1515)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1494)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1484)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityPlayer.enderTeleportTo(EntityPlayer.java:1772)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.a(EntityLiving.java:2272)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.stopRiding(EntityLiving.java:3059)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityHuman.stopRiding(EntityHuman.java:1058)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityPlayer.stopRiding(EntityPlayer.java:1384)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.EntityPlayer.stopRiding(EntityPlayer.java:1379)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.Entity.ejectPassengers(Entity.java:2163)
[13:42:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.entity.CraftEntity.eject(CraftEntity.java:701)
[13:42:04 WARN]:        at org.popcraft.chunky.platform.BukkitPlayer.teleport(BukkitPlayer.java:76)
[13:42:04 WARN]:        at org.popcraft.chunkyborder.BorderCheckTask.lambda$run$0(BorderCheckTask.java:47)
[13:42:04 WARN]:        at java.base/java.util.Optional.ifPresent(Optional.java:178)
[13:42:04 WARN]:        at org.popcraft.chunkyborder.BorderCheckTask.run(BorderCheckTask.java:29)
[13:42:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:101)
[13:42:04 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:485)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1432)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[13:42:04 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:42:04 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
```

enderpearl
```[13:43:06 WARN]: java.lang.NoSuchMethodError: 'int org.bukkit.World.getLogicalHeight()'
[13:43:06 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevationForLocation(BukkitWorld.java:142)
[13:43:06 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevation(BukkitWorld.java:136)
[13:43:06 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$4(ChunkyBorder.java:122)
[13:43:06 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[13:43:06 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$5(ChunkyBorder.java:84)
[13:43:06 WARN]:        at org.popcraft.chunky.event.EventBus.lambda$call$2(EventBus.java:52)
[13:43:06 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[13:43:06 WARN]:        at org.popcraft.chunky.event.EventBus.call(EventBus.java:50)
[13:43:06 WARN]:        at org.popcraft.chunkyborder.ChunkyBorderBukkit.onPlayerTeleport(ChunkyBorderBukkit.java:237)
[13:43:06 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source)
[13:43:06 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:43:06 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:43:06 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:43:06 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.EntityEnderPearl.a(EntityEnderPearl.java:69)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.IProjectile.preOnHit(IProjectile.java:141)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.EntityProjectile.tick(EntityProjectile.java:70)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.EntityEnderPearl.tick(EntityEnderPearl.java:109)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.entityJoinedWorld(WorldServer.java:960)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.World.a(World.java:955)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.WorldServer.doTick(WorldServer.java:646)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1495)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[13:43:06 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:43:06 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
```

chorus
```[13:44:08 WARN]: java.lang.NoSuchMethodError: 'int org.bukkit.World.getLogicalHeight()'
[13:44:08 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevationForLocation(BukkitWorld.java:142)
[13:44:08 WARN]:        at org.popcraft.chunky.platform.BukkitWorld.getElevation(BukkitWorld.java:136)
[13:44:08 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$4(ChunkyBorder.java:122)
[13:44:08 WARN]:        at java.base/java.util.Optional.map(Optional.java:260)
[13:44:08 WARN]:        at org.popcraft.chunkyborder.ChunkyBorder.lambda$subscribeEvents$5(ChunkyBorder.java:84)
[13:44:08 WARN]:        at org.popcraft.chunky.event.EventBus.lambda$call$2(EventBus.java:52)
[13:44:08 WARN]:        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[13:44:08 WARN]:        at org.popcraft.chunky.event.EventBus.call(EventBus.java:50)
[13:44:08 WARN]:        at org.popcraft.chunkyborder.ChunkyBorderBukkit.onPlayerTeleport(ChunkyBorderBukkit.java:237)
[13:44:08 WARN]:        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor19.execute(Unknown Source)
[13:44:08 WARN]:        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69)
[13:44:08 WARN]:        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80)
[13:44:08 WARN]:        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
[13:44:08 WARN]:        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1515)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.safeTeleport(EntityLiving.java:3504)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.ItemChorusFruit.a(ItemChorusFruit.java:37)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.ItemStack.a(ItemStack.java:438)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.s(EntityLiving.java:3362)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityPlayer.s(EntityPlayer.java:1682)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.t(EntityLiving.java:3213)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityLiving.tick(EntityLiving.java:2544)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityHuman.tick(EntityHuman.java:258)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.EntityPlayer.playerTick(EntityPlayer.java:658)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.PlayerConnection.tick(PlayerConnection.java:325)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.NetworkManager.a(NetworkManager.java:408)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.ServerConnection.c(ServerConnection.java:168)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1520)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:436)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1347)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1135)
[13:44:08 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291)
[13:44:08 WARN]:        at java.base/java.lang.Thread.run(Thread.java:842)
```

**Comment by pop4959** [comment]
Sorry I saw this last week, but must have forgotten to respond. It looks like you are probably using the wrong version of Chunky and ChunkyBorder for your Minecraft version. Make sure you download the correct ones and especially that the version of the addon was released at the same time as the chunky version you have (for best compatibility).

If you still need help with this, please join the Discord server - you will also get a much faster answer there for simple troubleshooting questions like this.
