### ISSUE TITLE
Error on startup preventing ChunkyBorder from loading

### ISSUE THREAD

**Issue by DarkChromaMC** [pop4959/ChunkyBorder#78]
I get the following error during startup when attempting to load the Chunky plugin
```
[14:22:49 ERROR]: [DirectoryProviderSource] Error loading plugin: java.lang.IllegalArgumentException: Directory 'plugins/ChunkyBorder-1.2.18.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
java.lang.RuntimeException: java.lang.IllegalArgumentException: Directory 'plugins/ChunkyBorder-1.2.18.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        at io.papermc.paper.plugin.provider.source.FileProviderSource.registerProviders(FileProviderSource.java:86) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:52) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paper.plugin.provider.source.DirectoryProviderSource.registerProviders(DirectoryProviderSource.java:17) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paper.plugin.util.EntrypointUtil.registerProvidersFromSource(EntrypointUtil.java:15) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paper.plugin.PluginInitializerManager.load(PluginInitializerManager.java:113) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at net.minecraft.server.Main.main(Main.java:123) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paper.PaperBootstrap.boot(PaperBootstrap.java:21) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at org.bukkit.craftbukkit.Main.main(Main.java:298) ~[axolotl-1.21.jar:1.21-DEV-f16f3da]
        at io.papermc.paperclip.Paperclip.lambda$main$0(Paperclip.java:42) ~[app:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.IllegalArgumentException: Directory 'plugins/ChunkyBorder-1.2.18.jar' does not contain a paper-plugin.yml or plugin.yml! Could not determine plugin type, cannot load a plugin from it!
        ... 10 more
```

Any clue what might be causing it? I have Chunky installed.

Thank you!

**Comment by pop4959** [comment]
Hi, it looks like you downloaded something that is not a plugin, as indicated by the error you have. Chunky comes as a plugin or mod, so pay attention closely to which you have downloaded. I recommend re-downloading the correct version for Bukkit/Paper and it should work. If you still have any questions or run into issues please join the Discord support server.
