### ISSUE TITLE
Players able to use vehicles to bypass border on Folia 1.20.6

### ISSUE THREAD

**Issue by Technicolor-creamsicle** [pop4959/ChunkyBorder#79]
On Folia 1.20.6 players are able to pass through the border on vehicles but are not teleported back as chunky is attempting to teleport them away on the wrong thread.

- Folia 1.20.6
- Chunky Border 1.2.13
- Chunky 1.4.10

```
[14:11:05] [Region Scheduler Thread #3/ERROR]: Thread Region Scheduler Thread #3 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftBoat.getHandle(CraftBoat.java:114) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftBoat.getHandle(CraftBoat.java:10) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at org.bukkit.craftbukkit.entity.CraftEntity.getPassengers(CraftEntity.java:438) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at Chunky.jar/org.popcraft.chunky.platform.BukkitPlayer.teleport(BukkitPlayer.java:75) ~[Chunky.jar:?]
	at ChunkyBorder.jar/org.popcraft.chunkyborder.BorderCheckTask.lambda$run$0(BorderCheckTask.java:47) ~[ChunkyBorder.jar:?]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at ChunkyBorder.jar/org.popcraft.chunkyborder.BorderCheckTask.run(BorderCheckTask.java:29) ~[ChunkyBorder.jar:?]
	at Chunky.jar/org.popcraft.chunky.platform.Folia.lambda$scheduleFixedGlobal$1(Folia.java:29) ~[Chunky.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.6.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.6.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.6.jar:1.20.6-DEV-d797082]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]```

**Comment by pop4959** [comment]
Have you tried updating chunky? This should have been fixed in a [newer version](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/).

**Comment by pop4959** [comment]
Closing due to no response. I am fairly certain this is a duplicate. Let me know if not and I can re-open.
