### ISSUE TITLE
folia error keep spamming 1.20.4

### ISSUE THREAD

**Issue by cgw2023** [pop4959/ChunkyBorder#81]
folia-bundler-1.20.4-R0.1-SNAPSHOT-reobf-ec6b172
Chunky-1.4.10
ChunkyBorder-1.2.13

```[15:35:34] [Region Scheduler Thread #14/ERROR]: Thread Region Scheduler Thread #14 failed main thread check: Accessing entity state off owning region's thread
java.lang.Throwable: null
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:78) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftArmorStand.getHandle(CraftArmorStand.java:32) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftArmorStand.getHandle(CraftArmorStand.java:12) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getPassengers(CraftEntity.java:438) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.popcraft.chunky.platform.BukkitPlayer.teleport(BukkitPlayer.java:75) ~[Chunky-1.4.10.jar:?]
	at org.popcraft.chunkyborder.BorderCheckTask.lambda$run$0(BorderCheckTask.java:47) ~[ChunkyBorder-1.2.13.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.popcraft.chunkyborder.BorderCheckTask.run(BorderCheckTask.java:29) ~[ChunkyBorder-1.2.13.jar:?]
	at org.popcraft.chunky.platform.Folia.lambda$scheduleFixedGlobal$1(Folia.java:29) ~[Chunky-1.4.10.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[15:35:34] [Region Scheduler Thread #14/WARN]: [ChunkyBorder] Global task for ChunkyBorder v1.2.13 generated an exception
java.lang.IllegalStateException: Accessing entity state off owning region's thread
	at io.papermc.paper.util.TickThread.ensureTickThread(TickThread.java:79) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftArmorStand.getHandle(CraftArmorStand.java:32) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftArmorStand.getHandle(CraftArmorStand.java:12) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.bukkit.craftbukkit.v1_20_R3.entity.CraftEntity.getPassengers(CraftEntity.java:438) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at org.popcraft.chunky.platform.BukkitPlayer.teleport(BukkitPlayer.java:75) ~[Chunky-1.4.10.jar:?]
	at org.popcraft.chunkyborder.BorderCheckTask.lambda$run$0(BorderCheckTask.java:47) ~[ChunkyBorder-1.2.13.jar:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at org.popcraft.chunkyborder.BorderCheckTask.run(BorderCheckTask.java:29) ~[ChunkyBorder-1.2.13.jar:?]
	at org.popcraft.chunky.platform.Folia.lambda$scheduleFixedGlobal$1(Folia.java:29) ~[Chunky-1.4.10.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler$GlobalScheduledTask.run(FoliaGlobalRegionScheduler.java:179) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.scheduler.FoliaGlobalRegionScheduler.tick(FoliaGlobalRegionScheduler.java:37) ~[folia-1.20.4.jar:?]
	at io.papermc.paper.threadedregions.RegionizedServer.globalTick(RegionizedServer.java:293) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.RegionizedServer$GlobalTickTickHandle.tickRegion(RegionizedServer.java:148) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at io.papermc.paper.threadedregions.TickRegionScheduler$RegionScheduleHandle.runTick(TickRegionScheduler.java:404) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at ca.spottedleaf.concurrentutil.scheduler.SchedulerThreadPool$TickThreadRunner.run(SchedulerThreadPool.java:525) ~[folia-1.20.4.jar:git-Folia-"ec6b172"]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
```

**Comment by pop4959** [comment]
Download an updated version of [chunky](https://ci.codemc.io/view/Author/job/pop4959/job/Chunky/), looks like this was already fixed a few months ago here: https://github.com/pop4959/Chunky/pull/347
