### ISSUE TITLE
Bug report: Exception thrown on start up when world are unloaded by default (but unloaded by something else than multiverse)

### ISSUE THREAD

**Issue by Over2Craft-mc** [pop4959/ChunkyBorder#9]
When using [PlayerWorldsPro ](https://www.spigotmc.org/resources/%E2%AD%90-playerworldspro-%E2%AD%90-the-nether-and-the-end-support-expiration-1-8-1-16-4.72113/) (a plugin that allow players to create their own world) 

If PlayerWorldsPro's configuration below is enabled
```yaml
  # All player worlds load on startup.
  Load-On-Startup: false
```

CB is going to thrown an exception on startup for each worlds that are not loaded. 

```
[08:39:28] [Server thread/ERROR]: Could not pass event WorldLoadEvent to ChunkyBorder v1.0.23
java.lang.NullPointerException: null
	at org.popcraft.chunkyborder.ChunkyBorder.onWorldLoad(ChunkyBorder.java:199) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor277.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-443]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.createWorld(CraftServer.java:1171) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.Bukkit.createWorld(Bukkit.java:590) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.WorldCreator.createWorld(WorldCreator.java:325) ~[patched_1.16.5.jar:git-Paper-443]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:499) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:480) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.doLoad(WorldManager.java:455) ~[?:?]
	at com.onarandombox.MultiverseCore.utils.WorldManager.loadWorlds(WorldManager.java:767) ~[?:?]
	at com.onarandombox.MultiverseCore.MultiverseCore.onEnable(MultiverseCore.java:307) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-443]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-443]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:464) ~[patched_1.16.5.jar:git-Paper-443]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:239) ~[patched_1.16.5.jar:git-Paper-443]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:935) ~[patched_1.16.5.jar:git-Paper-443]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:173) ~[patched_1.16.5.jar:git-Paper-443]
```

**Comment by Over2Craft-mc** [comment]
Looks fixed in [#55c423c](https://github.com/pop4959/ChunkyBorder/commit/55c423c3362cd6b5e696e20e2bcc85c7208d32a0)
